import { FieldsEnum } from './features/AddDetection/Components/AddFieldsToDetectionForm/types';

export const MOCK_USER = {
  id: 'user1',
  name: 'Commander Ivanov',
  password: 'hashed_password_123',
  networkCommunication: [
    {
      id: 'net1',
      name: 'Black Sea Fleet Network',
      userId: 'user1',
      template: {
        id: 'tmpl1',
        networkId: 'net1',
        timeOfDetection: FieldsEnum.REQUIRED,
        timeFrom: FieldsEnum.OFF,
        timeTo: FieldsEnum.OFF,
        abonentFrom: FieldsEnum.ON,
        abonentTo: FieldsEnum.ON,
        abonentCircular: FieldsEnum.OFF,
        frequency: FieldsEnum.REQUIRED,
        pelengsImg: FieldsEnum.OFF,
        lat: FieldsEnum.OFF,
        lng: FieldsEnum.OFF,
        map: FieldsEnum.OFF,
        additionalInformation: FieldsEnum.OFF,
        transmissionType: FieldsEnum.ON,
      },
      detections: [
        {
          id: 'det1',
          networkId: 'net1',
          timeOfDetection: '2025-11-13T08:33:00Z',
          timeFrom: '2025-11-13T08:30:00Z',
          timeTo: '2025-11-13T08:32:00Z',
          frequency: '1247.5',
          pelengsImg: 45.3,
          lat: 44.6167,
          lng: 33.525,
          additionalInformation: false,
          transmissionType: {
            id: 'tr1',
            name: 'HF Voice',
          },
          abonentFrom: {
            id: 'ab1',
            detectionId: 'det1',
            callsign: 'from callsign 1',
            peleng: '112',
            objects: [
              {
                type: 'ship_base',
                id: 'ship1',
                name: 'Admiral Essen',
                bortNumber: '751',
                project: '11356R',
                unit: {
                  id: 'unit1',
                  name: '1st Naval Division',
                  callsign: 'ND-01',
                },
              },
            ],
          },
          abonentTo: {
            id: 'ab2',
            detectionId: 'det1',
            callsign: 'from callsign 2',
            peleng: '250',
            objects: [
              {
                type: 'ship_base',
                id: 'ship2',
                name: 'Admiral Makarov',
                bortNumber: '799',
                project: '11356R',
                unit: {
                  id: 'unit1',
                  name: '1st Naval Division',
                  callsign: 'ND-01',
                },
              },
            ],
          },
          abonentCircular: null,
        },
        {
          id: 'det2',
          networkId: 'net1',
          timeOfDetection: '2025-11-13T09:15:00Z',
          timeFrom: '2025-11-13T09:00:00Z',
          timeTo: '2025-11-13T09:05:00Z',
          frequency: '3344.5',
          pelengsImg: 90.2,
          lat: 45.1234,
          lng: 36.6543,
          additionalInformation: true,
          transmissionType: {
            id: 'tr2',
            name: 'UHF Data',
          },
          abonentFrom: {
            id: 'ab3',
            detectionId: 'det2',
            callsign: 'from callsign 1',
            peleng: '112',
            objects: [
              {
                type: 'unit',
                id: 'unit2',
                name: 'Coastal Support Division',
                callsign: 'CSD-02',
              },
            ],
          },
          abonentTo: {
            id: 'ab4',
            detectionId: 'det2',
            callsign: 'from callsign 1',
            peleng: '112',
            objects: [
              {
                type: 'ship_base',
                id: 'ship1',
                name: 'Admiral Essen',
                bortNumber: '751',
                project: '11356R',
                unit: {
                  id: 'unit1',
                  name: '1st Naval Division',
                  callsign: 'ND-01',
                },
              },
            ],
          },
          abonentCircular: null,
        },
      ],
    },
    {
      id: 'net2',
      name: 'Black Sea Fleet Network',
      userId: 'user1',
      template: {
        timeOfDetection: FieldsEnum.REQUIRED,
        timeFrom: FieldsEnum.OFF,
        timeTo: FieldsEnum.OFF,
        abonentFrom: FieldsEnum.ON,
        abonentTo: FieldsEnum.ON,
        abonentCircular: FieldsEnum.OFF,
        frequency: FieldsEnum.REQUIRED,
        pelengsImg: FieldsEnum.OFF,
        lat: FieldsEnum.OFF,
        lng: FieldsEnum.OFF,
        map: FieldsEnum.OFF,
        additionalInformation: FieldsEnum.OFF,
        transmissionType: FieldsEnum.ON,
      },
      detections: [
        {
          id: 'det1',
          networkId: 'net2',
          timeOfDetection: '2025-11-13T08:33:00Z',
          timeFrom: '2025-11-13T08:30:00Z',
          timeTo: '2025-11-13T08:32:00Z',
          frequency: '5555',
          pelengsImg: 45.3,
          lat: 44.6167,
          lng: 33.525,
          additionalInformation: false,
          transmissionType: {
            id: 'tr1',
            name: 'HF Voice',
          },
          abonentFrom: {
            id: 'ab1',
            detectionId: 'det1',
            callsign: 'from callsign 1',
            peleng: '112',
            objects: [
              {
                type: 'ship_base',
                id: 'ship1',
                name: 'Admiral Essen',
                bortNumber: '751',
                project: '11356R',
                unit: {
                  id: 'unit1',
                  name: '1st Naval Division',
                  callsign: 'ND-01',
                },
              },
            ],
          },
          abonentTo: {
            id: 'ab2',
            detectionId: 'det1',
            callsign: 'from callsign 1',
            peleng: '112',
            objects: [
              {
                type: 'ship_base',
                id: 'ship2',
                name: 'Admiral Makarov',
                bortNumber: '799',
                project: '11356R',
                unit: {
                  id: 'unit1',
                  name: '1st Naval Division',
                  callsign: 'ND-01',
                },
              },
            ],
          },
          abonentCircular: null,
        },
        {
          id: 'det2',
          networkId: 'net2',
          timeOfDetection: '2025-11-13T09:15:00Z',
          timeFrom: '2025-11-13T09:00:00Z',
          timeTo: '2025-11-13T09:05:00Z',
          frequency: '3344.5',
          pelengsImg: 90.2,
          lat: 45.1234,
          lng: 36.6543,
          additionalInformation: true,
          transmissionType: {
            id: 'tr2',
            name: 'UHF Data',
          },
          abonentFrom: {
            id: 'ab3',
            detectionId: 'det2',
            callsign: 'from callsign 1',
            peleng: '112',
            objects: [
              {
                type: 'unit',
                id: 'unit2',
                name: 'Coastal Support Division',
                callsign: 'CSD-02',
              },
            ],
          },
          abonentTo: {
            id: 'ab4',
            detectionId: 'det2',
            callsign: 'from callsign 1',
            peleng: '112',
            objects: [
              {
                type: 'ship_base',
                id: 'ship1',
                name: 'Admiral Essen',
                bortNumber: '751',
                project: '11356R',
                unit: {
                  id: 'unit1',
                  name: '1st Naval Division',
                  callsign: 'ND-01',
                },
              },
            ],
          },
          abonentCircular: null,
        },
      ],
    },
  ],
};
